### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by FracKenA** [simplificator/sitincator#15]
Your README.ME states

> To add a custom title to the screens (e.g. to identify a specific room this display is for), edit sitincator.json (created during the calendar ID setup) and modify the title entry.

However the json genereated **Sitincator/resources/app/config/sitincator.json** only contains 
{"calendar_id":"MyCalendarID"}

What json element do I need to add?

**Comment by phylor** [comment]
Although that feature was merged into the `master` branch, it has not yet been released. I added it to [v1.0.4](https://github.com/simplificator/sitincator/releases/tag/v1.0.4).

Please have another look. The element is called `title`, so it should look like:

```
{"calendar_id": "MyCalendarID", title: "My Title"}
```

**Comment by FracKenA** [comment]
No longer valid post merge.
