### ISSUE TITLE
I need help - Please advise

### ISSUE THREAD

**Issue by faheemwahid** [simplificator/sitincator#19]
Hi dear,

I need some help. I am asked at my college to build a MEETING ROOM Status DISPLAY.

my college have provided me all the Hardware - Raspberry pi3, 7inch touch display and memory card. i would like to learn from the scratch that what do i need to do. i read loads of thread and post on different website and also got a full package of software on GITHUB but it is not enough as i am missing somewhere. 

if you can help me to build this - it would be great.

I like this one and this is exactly what i need that i have 3 meetings rooms and have to prepare 3 calendars for all the rooms and entered the meeting details in the calendar and it should display. see below:

There is only one thing - i am asked that if possible then i should be able to do this if there is no internet but all the Raspberry will be in the network and if i would still be able to display - possibly by using fullcalendar.io or google offline calendar. i do have a lot of ideas but i don't know how to put things in order.

what i need is to someone guide me and help me while i am stuck in the middle as this is very important for me to do it.

i can follow the guidance easily.

Looking forward for some support,

Thank you,

Best Regards

Faheem W.

**Comment by Zinggi** [comment]
Hi Faheem

Unfortunately sitincator is just a small side project and we don't have the resources to actually provide you with support for your specific situation. 
We are open to contributions, but we will not be working on things we don't need ourself.
 So I'm really sorry, but I can't help you out here.

Best regards,
Florian
