### ISSUE TITLE
electron.asar missing

### ISSUE THREAD

**Issue by josearellanodev** [simplificator/sitincator#2]
Thank you so much for this app.  So useful!

After using the new build, I tried running the executable, I get this error:

pi@raspberrypi:~/Sitincator $ ./Sitincator 
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/pi/Sitincator/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:428:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:548:3

I do have a /resources/ directory but it does not have any files.

Any suggestions?

Thanks again!

**Comment by phylor** [comment]
@josefdigarbanzo Sorry for not getting any response on your issue. If the `resources` directory is empty, something went wrong during packaging. There are now binaries available which should work out of the box. The installation instructions in the `README` have also been improved and should now work much better.

Closing, please open a new issue if you are still encountering an issue!
