### ISSUE TITLE
Rejects Client Secret JSON

### ISSUE THREAD

**Issue by seasilvia** [simplificator/sitincator#3]
I'm trying to use the quick install method, and after getting the api key which looks like:

{"web":{"client_id":"(redacted).apps.googleusercontent.com","project_id":"(redacted)","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"(redacted)"}}

When placed in `resources/app/config/client_secret.json`, the following error occurs:

```
$ ./Sitincator
TypeError: Cannot read property 'client_secret' of undefined
    at readCredentials.then.credentials (/home/pi/Sitincator/resources/app/src/gcal/index.js:122:49)
```

Is my client_secret misformatted?  Any idea what's causing the problem?

**Comment by egitto** [comment]
Yes, your `client_secret.json` is either misformatted or you're using the wrong thing for it. Yours looks like this:
```
{
  "web":
  {
    "client_id":"(redacted).apps.googleusercontent.com",
    "project_id":"(redacted)",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"(redacted)"
  }
}
```
but it's expected to look more like this:
```
{
  "installed":
  {
    "client_id":"redacted.apps.googleusercontent.com",
    "project_id":"redacted",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"redacted",
    "redirect_uris":
    [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost" 
    ]
  }
}
```
You could try to reformat your file, but that's probably the wrong approach, especially yours has no redirect uris. You should probably follow the steps on this page (step 1 yielded the sample I showed), which should yield an appropriately formatted file. https://developers.google.com/google-apps/calendar/quickstart/nodejs#step_1_turn_on_the_api_name

**Comment by joelrader** [comment]
I was hung up on this same spot, but re-read the instructions and was able to get the right token upload. Now, I'm stuck on the next step. I've signed in, obtained my API token, but then the application crashed:

Error: ENOENT: no such file or directory. open 'credentials/token.json'
errno: -2
code 'ENOENT'
syscall: 'open',
path: 'credentials/token.json'

What does any of that mean?

**Comment by phylor** [comment]
@raiderj This was indeed a bug in the application. Could you please try the newest release, v1.0.3?

**Comment by joelrader** [comment]
Tried again.... did an `rm -rf Sitincator` on my home directory, then did another install. Right now it seems to have timed out after I entered a calendar ID.

I see an entry just above the calendar ID request: `Sitincator: no process found`. Does that mean anything?

**Comment by phylor** [comment]
@raiderj I noticed that the install script hangs. Abort that. Have you already copied/created `client_secret.json`? Make sure it is at `resources/app/config/client_secret.json` and then run `/home/pi/Sitincator/Sitincator`. It asks again for the calendar ID, but it then should retrieve the token.

**Comment by joelrader** [comment]
Understood - will try again with the token.

**Comment by joelrader** [comment]
@phylor 

That worked! I ran the script, exited out when it asked for the Calendar ID, copied over the JSON token, then ran Sitincator. Had to copy the URL, open a browser to paste it in, authenticate my Gmail account, then copy the code back to the script. After that I see the Quick Booking screen pop up.

Thanks! Will test this out over the next week.

**Comment by phylor** [comment]
@raiderj Perfect, glad you got it working! Sorry for the trouble, I'll improve the installation script.

Closing this issue, please get back to us if you're encountering any other issues with it or if you have feedback about it!

**Comment by GreyJedi73** [comment]
In my case, it still asked for the Calendar ID even after I had copied across the client_secret.JSON. Only this time, inserting the Calendar ID produces a link. Copying the link and opening it on a web browser takes me to a page with an API key. When I paste this key in the terminal, then does the application launch. But there's another hurdle: the calendar is completely empty. Even when I book a dummy appointment on my computer and set the appointment time to five minutes from the present moment, it does not register on the screen.
