### ISSUE TITLE
Sitincator got slow on RPI3

### ISSUE THREAD

**Issue by toelke** [simplificator/sitincator#8]
Hi all,

we tried Sitincator in June and decided to use it for our Meeting-Rooms. Now I had time to further that project and am very happy about the development that happened since then!

In June however any screen transition was fluid. Now its very laggy. I tried both the release build and built it myself.

Is anyone else seeing this problem? Is there anything I can do to debug this? How easy would it to be to disable animated transitions?

Thanks!

Philipp

**Comment by toelke** [comment]
As it turns out, I did not enable VC4 when re-installing everything.

For the record, "dtoverlay=vc4-fkms-v3d" is needed, the -kms- caused my Pi to just show a black screen and not boot.

Also, I since found the sass-files where I could disable the transitions. Now that everything is fast again, I might re-enable them...

Sorry for the noise!

Regards,
Philipp

**Comment by phylor** [comment]
Interesting, glad you figured it out!
