### ISSUE TITLE
Feature Request: Add Calendar ID or Alias to main screen

### ISSUE THREAD

**Issue by joelrader** [simplificator/sitincator#9]
It'd be great to have a logo and text on the screen in addition to the calendar. Many meeting rooms have an alias in addition to an official room number that may not match the actual calendar ID too. It'd be great to display the calendar ID so people know where to send invite requests on top of a common name.

**Comment by shevett** [comment]
I've just coded this and put in a pull request to merge it in.

**Comment by shevett** [comment]
Looks like the pull request hasn't gotten accepted yet.  You can see it here on my branch if you like - i'll be merging it into my fork shortly and working on some other features as well.  https://github.com/shevett/sitincator/tree/shevett-dec02

**Comment by phylor** [comment]
Thanks to @shevett it's now possible to display a title. @raiderj, you could include whatever information you'd like there (calendar ID, etc.). It's configurable in `sitincator.json`.

Merged in https://github.com/simplificator/sitincator/commit/5aaa5a07f7f1ed1177d9f7bab5809c1265a4fa90
